#!/bin/bash

# Check QEMU behaviour against test logs generated by hardware.

QEMU=qemu-system-avr
TEMP=/tmp/test-log

for FILE_BIN in bin/*.elf; do
	# Build the path to the debug log from hardware for this test program
	FILE_LOG=$(echo "$FILE_BIN" | sed 's/^bin/logs/' | sed 's/\.elf$/-AVR.log/')
	echo "Checking $FILE_BIN..."
	echo "    (log file $FILE_LOG)" # TODO
	# Sanity check existence of files
	if [ ! -f "$FILE_LOG" ]; then
		echo "Couldn't find hardware log file '$FILE_LOG', have you unpacked the archived log files?"
		exit 1
	fi
	# Run QEMU and dump the debug trace for comparison
	$QEMU -s -S -M mega2560 -bios "$FILE_BIN" &> /dev/null &
	avr-gdb -x run-all.gdb "$FILE_BIN" &> "$TEMP"
	# Ask QEMU to stop once program is done, then wait for everything to finish
	kill -s 2 $!
	wait
	# Compare debug log from the test with the stored hardware log
	# Some spurious differences are ignored
	if diff --suppress-common-lines \
		-I 'Inferior 1 \[.*\] will be' \
		-I '^0x00000000 in __vectors' \
		-I '^50	break' \
		-I '^74	break' \
		-I "^unknown command: 'reset'" \
		-I '^main () at generated/BAC.S:50' \
		-I '^main () at generated/LS.S:74' \
		-I '^warning: Target-supplied registers are not supported by the current architecture$' \
		-y "$TEMP" "$FILE_LOG"
	then
		echo "    OK"
	else
		echo "    FAIL (logs differ, see QEMU and diff output above)"
	fi
done
